# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  docker:
  # specify the version you desire here
  - image: circleci/openjdk:11-jdk
  working_directory: ~
  environment:
    # Customize the JVM maximum heap limit
    _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
    TERM: dumb
version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - attach_workspace:
        at: .
    - run:
        name: get common
        command: |
          git clone "https://3e098c9a5365bee38e3281b33ac045fb87b634fb:x-oauth-basic@github.com/Founder-Pro/founder-t1-account-batch.git"
          git checkout master
